; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=agc -verify-machineinstrs < %s | FileCheck %s

; Check that basic ALU operations can be lowered to AGC instructions.

define i16 @add(i16 %a, i16 %b) {
; CHECK-LABEL: add:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ca r50
; CHECK-NEXT:    ad r51
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    tc 2
entry:
  %0 = add i16 %a, %b
  ret i16 %0
}

define i16 @sub(i16 %a, i16 %b) {
; CHECK-LABEL: sub:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ca r50
; CHECK-NEXT:    extend
; CHECK-NEXT:    su r51
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    tc 2
entry:
  %0 = sub i16 %a, %b
  ret i16 %0
}

define i16 @and(i16 %a, i16 %b) {
; CHECK-LABEL: and:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ca r50
; CHECK-NEXT:    mask r51
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    tc 2
entry:
  %0 = and i16 %a, %b
  ret i16 %0
}
