; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=agc -verify-machineinstrs < %s | FileCheck %s

; Check that args are appearing in the right locations according to the calling
; convention.

define i16 @args_1xi16(i16 %a) {
; CHECK-LABEL: args_1xi16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    tc 2
entry:
  ret i16 %a
}

define i16 @args_2xi16(i16, i16 %b) {
; CHECK-LABEL: args_2xi16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ca r51
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    tc 2
entry:
  ret i16 %b
}

define i16 @args_3xi16(i16, i16, i16 %c) {
; CHECK-LABEL: args_3xi16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ca r52
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    tc 2
entry:
  ret i16 %c
}

define i32 @args_1xi32(i32 %a) {
; CHECK-LABEL: args_1xi32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    tc 2
entry:
  ret i32 %a
}

define i32 @args_2xi32(i32, i32 %b) {
; CHECK-LABEL: args_2xi32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    extend
; CHECK-NEXT:    dca rd52
; CHECK-NEXT:    xch l
; CHECK-NEXT:    ts r51
; CHECK-NEXT:    xch l
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    tc 2
entry:
  ret i32 %b
}

define i32 @args_1xi16_1xi32(i16, i32 %b) {
; CHECK-LABEL: args_1xi16_1xi32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    extend
; CHECK-NEXT:    dca rd52
; CHECK-NEXT:    xch l
; CHECK-NEXT:    ts r51
; CHECK-NEXT:    xch l
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    tc 2
entry:
  ret i32 %b
}
