; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=agc -verify-machineinstrs < %s | FileCheck %s

define i16 @load(i16* %ptr) {
; CHECK-LABEL: load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    index r50
; CHECK-NEXT:    ca 0
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    tc 2
entry:
  %0 = load i16, i16* %ptr
  ret i16 %0
}

define i16 @load_offs(i16* %ptr) {
; CHECK-LABEL: load_offs:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    index r50
; CHECK-NEXT:    ca 2
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    tc 2
entry:
  %0 = ptrtoint i16* %ptr to i16
  %1 = add i16 %0, 2
  %2 = inttoptr i16 %1 to i16*
  %3 = load i16, i16* %2
  ret i16 %3
}
