; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=agc -verify-machineinstrs < %s | FileCheck %s

define i16 @use_many(i16 %a, i16 %b, i16 %c, i16 %d) {
; CHECK-LABEL: use_many:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ca %cpi(4)
; CHECK-NEXT:    ad sp
; CHECK-NEXT:    ts sp
; CHECK-NEXT:    ca r50
; CHECK-NEXT:    xch r51
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    xch r51
; CHECK-NEXT:    ad r50
; CHECK-NEXT:    index sp
; CHECK-NEXT:    ts 0
; CHECK-NEXT:    ca r51
; CHECK-NEXT:    xch r52
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    xch r52
; CHECK-NEXT:    ad r50
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    index sp
; CHECK-NEXT:    ca 0
; CHECK-NEXT:    ad r50
; CHECK-NEXT:    index sp
; CHECK-NEXT:    ts 0
; CHECK-NEXT:    ca r52
; CHECK-NEXT:    ad r53
; CHECK-NEXT:    index sp
; CHECK-NEXT:    ts 2
; CHECK-NEXT:    index sp
; CHECK-NEXT:    ca 0
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    index sp
; CHECK-NEXT:    ca 2
; CHECK-NEXT:    ad r50
; CHECK-NEXT:    ts r50
; CHECK-NEXT:    ca %cpi(4)
; CHECK-NEXT:    extend
; CHECK-NEXT:    su sp
; CHECK-NEXT:    ts sp
; CHECK-NEXT:    tc 2
entry:
  %0 = add i16 %a, %b
  %1 = add i16 %b, %c
  %2 = add i16 %c, %d
  %3 = add i16 %0, %1
  %4 = add i16 %2, %3
  ret i16 %4
}
